### ISSUE TITLE
Dragged item is being overlapped by other items even with z-index 

### ISSUE THREAD

**Issue by hingoman25** [adopted-ember-addons/ember-sortable#320]
**Describe the bug**
When I drag an item some parts of another item overlap it. Also when I drag an item, it sometimes goes underneath another list item which does not seem like normal behavior. All dragged items should hover above other items.

**Expected behavior**
I expect the dragged item to always hover over other items when dragged.

**Screenshots**

![example](https://user-images.githubusercontent.com/13734160/68505725-cbd07e80-021c-11ea-96a2-b45a6450615c.gif)

This gif represents the dragged item being overlapped by some fields in another item and the dragged item going underneath other items. 

<img width="417" alt="Screen Shot 2019-11-08 at 11 44 18 AM" src="https://user-images.githubusercontent.com/13734160/68505855-1d790900-021d-11ea-947a-097940f96937.png">

**Comment by knownasilya** [comment]
Looks like there are two issues, one is that your item has a transparent background when dragged, but the other issue is related to order. The order issue is a bug I believe, but the other should be solved on a per implementation basis, so in your app.

**Comment by hingoman25** [comment]
I should have included the code for the background but even with the dragged item's background set to a solid white, the issue still occurs. If you look closely, it only occurs when the dragged item passes through half of the stationery item. I might have to look deeper into this issue but just wanted to check whether you guys have seen this behavior before.

**Comment by knownasilya** [comment]
@hingoman25 any chance you could make a repo with the reproduced example in it?

**Comment by hingoman25** [comment]
Unfortunately, it's company code so I won't be able to post it. I will try it figure it out since it's most likely an issue with my code. As for the order issue, how should we go about fixing that?

**Comment by hingoman25** [comment]
Found a fix: set the .sortable-item.is-dragging selector to position relative and a z-index of 10 or any other large number!
